services:

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "127.0.0.1:8761:8761"
    networks:
      - backend-network

networks:
  backend-network:
    external: true